### PR TITLE
Ad manager custom targeting companies

### PR DESCRIPTION
**Pull request by pullthefuse**
https://redmine.thedrum.com/issues/34553

Linked to: https://gitlab.com/thedrum-developers/thedrum.com/merge_requests/1051

### CODE REVIEW

**Review by chrisshennan — COMMENTED** [review]
I'm not sure of the use case for this but it looks like this is an additional (special) case which results in the same action being taken as the `$.each` above.

Is it possible to add this `user_company` information to the `tdDfpTargeting` object rather than adding an implementation specific change?

**Comment by pullthefuse** [comment]
Because of caching I need to add it in Javascript after its been rendered. How about we remove the `<script>` tags from the renderDfp method. So you would call it as follows:

```
<script language="javascript">
    {{ the_drum_dfp_render() }}
</script>
```
Then I can manipulate within the script tags and I get a cleaner code.

**Comment by chrisshennan** [comment]
Would the desired result not be achievable by changing the following?

```
{{ the_drum_dfp_render() }}
<script async src="/bundles/thedrumdfp/js/dfp.js"></script>
```

to

```
{{ the_drum_dfp_render() }}
<script language="javascript">
    if (gp !== undefined) {
        tdDfpTargeting.user_company = gp;
    }
</script>
<script async src="/bundles/thedrumdfp/js/dfp.js"></script>
```

**Comment by pullthefuse** [comment]
Yes that's what I have done. The OCD in me didn't like having the additional <script> tags!! Its ok not a big deal. If it can be considered for any future releases :)

**Pull request closed without merging**
